# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FA_AanchalBansal_0846324_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FA_AanchalBansal_0846324_iOS

pod 'SwiftyJSON'

end
